// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/pessoa/create.tsx";
import * as $4 from "./routes/pessoa/delete/[id].tsx";
import * as $5 from "./routes/pessoa/edit/[id].tsx";
import * as $6 from "./routes/pessoa/index.tsx";
import * as $7 from "./routes/pessoa/show/[id].tsx";
import * as $$0 from "./islands/Clock.tsx";
import * as $$1 from "./islands/ClockFunction.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/CounterComponent.tsx";
import * as $$4 from "./islands/ViewList.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/pessoa/create.tsx": $3,
    "./routes/pessoa/delete/[id].tsx": $4,
    "./routes/pessoa/edit/[id].tsx": $5,
    "./routes/pessoa/index.tsx": $6,
    "./routes/pessoa/show/[id].tsx": $7,
  },
  islands: {
    "./islands/Clock.tsx": $$0,
    "./islands/ClockFunction.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/CounterComponent.tsx": $$3,
    "./islands/ViewList.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
